### ISSUE TITLE
language

### ISSUE THREAD

**Issue by dhea1323** [tobiasvanderwerff/full-page-handwriting-recognition#1]
does it work with other languages that have the same characters as english?

**Comment by tobiasvanderwerff** [comment]
Hi,

You certainly can use the model on other languages that share the same vocabulary as English. If you have an alternative dataset that you want to train on, you could add a new Pytorch Dataset class in `src/data.py` that loads it. You could look at the class for the IAM dataset (`IAMDataset`) to get an idea of how this should be done.
