### ISSUE TITLE
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '\\C:\\Users\\harsh\\Downloads\\formsA-D\\formsA-D'

### ISSUE THREAD

**Issue by pontifex03** [tobiasvanderwerff/full-page-handwriting-recognition#10]
C:\Users\harsh\anaconda3\Lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Global seed set to 1337
Traceback (most recent call last):
  File "C:\Users\harsh\full-page-handwriting-recognition\src\main.py", line 326, in <module>
    main(args)
  File "C:\Users\harsh\full-page-handwriting-recognition\src\main.py", line 57, in main
    ds = IAMDataset(
         ^^^^^^^^^^^
  File "C:\Users\harsh\full-page-handwriting-recognition\src\data.py", line 76, in __init__
    self.data = self._get_forms()
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\harsh\full-page-handwriting-recognition\src\data.py", line 219, in _get_forms
    for img_path in dr.iterdir():
  File "C:\Users\harsh\anaconda3\Lib\pathlib.py", line 931, in iterdir
    for name in os.listdir(self):
                ^^^^^^^^^^^^^^^^
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '\\C:\\Users\\harsh\\Downloads\\formsA-D\\formsA-D'

any help would be appreciated

**Comment by tobiasvanderwerff** [comment]
Hi, it looks like there may be something wrong with the path you entered (the  '\C:\Users\harsh\Downloads\formsA-D\formsA-D' string). Is there perhaps a typo in there? I notice there is a ' \ ' at the beginning of the path, for example. Maybe try removing that? Let me know if that works.

**Comment by pontifex03** [comment]
![Screenshot 2023-09-07 193431](https://github.com/tobiasvanderwerff/full-page-handwriting-recognition/assets/97594548/aa81d14b-e880-41d4-b1dc-d74c9a0b0923)


can you please what is wrong in this?

**Comment by tobiasvanderwerff** [comment]
It seems to have something to do with the formatting of the string. Perhaps the " \ " characters should be escaped. You could try using double slashes instead of single ones: 'C:\\\Users\\\harsh\\\Downloads\\\formsA-D\\\formsA-D'

**Comment by pontifex03** [comment]
No luck ..its showing the same thing !!!

**Comment by tobiasvanderwerff** [comment]
Is the folder correct? I believe `--data_dir` is a folder that should contain 3 other folders: "formsA-D", "formsE-H", "formsI-Z". You could try removing the "formsA-D" from the string, i.e. `C:\Users\harsh\Downloads\`

**Comment by pontifex03** [comment]
![Screenshot 2023-09-07 232306](https://github.com/tobiasvanderwerff/full-page-handwriting-recognition/assets/97594548/4b9b0012-4988-4f46-ba43-43c037ab0e71)

**Comment by pontifex03** [comment]
so i put all 3 in that folder still the same

**Comment by tobiasvanderwerff** [comment]
The formatting of the path looks strange now. I would try double slash again, and if that doesn't work, try it with double quotes instead of single quotes.

**Comment by pontifex03** [comment]
![Screenshot 2023-09-08 011048](https://github.com/tobiasvanderwerff/full-page-handwriting-recognition/assets/97594548/7b1e2bfc-9712-4cbd-98bb-fb5b52d25005)

**Comment by pontifex03** [comment]
its with double quotes and double slash
i have formsA-D, formsE-H, formsI-Z these 3 folders in folder called data_dir whose path is  C:\\Users\\harsh\\Downloads\\data_dir

**Comment by tobiasvanderwerff** [comment]
It looks like you're missing files from the IAM dataset, in this case the files that should be in a folder called 'xml'. Make sure you have all the files from IAM in the data_dir folder.

**Comment by pontifex03** [comment]
Thankyou so much for the help ....its running now , how much time it takes to train ? I have nvidia rtx 3050 , 4gb graphics ; 16gb ram

**Comment by tobiasvanderwerff** [comment]
No worries, glad to hear it's working for you. 

Hard to say how long it will take on your specific hardware. I remember I was able to train the model in under 12 hours on a V100 GPU.
