### ISSUE TITLE
need to train model on full page images, form data

### ISSUE THREAD

**Issue by NeoDhirendra** [tobiasvanderwerff/full-page-handwriting-recognition#6]
hello i am trying to extract the text on doctor's prescription images, so i need to train the model on full page images, so what data should i use. IAM dataset form images doesn't have any labels file. if anyone has any pretrained model trained on full page images, pls share.

**Comment by tobiasvanderwerff** [comment]
Hi,

The IAM dataset _does_ include labels for the full page images. They are in XML format, so maybe that's why it's hard to find. You could try training on the form images and see how well it works for your dataset of doctor prescription images. Hope that helps.
