### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by nguyennampfiev** [tobiasvanderwerff/full-page-handwriting-recognition#8]
Thanks for sharing the implementation.
I have two questions related to your implementation.

First, did you conduct an experiment where you trained the model from scratch with a small number of sample data? I tried the same approach on my own dataset, but it seems like the model cannot converge.

Second, could you please share the pretrained model trained on the IAM dataset? I believe we could perform fine-tuning on it for a new language.

Thanks in advance

**Comment by tobiasvanderwerff** [comment]
Hi, 

It is a known issue that the model doesn't converge for form images (see the explanation at the top of the Readme). As to your second question, I'm afraid I do not have pretrained weights available.

**Comment by nguyennampfiev** [comment]
@tobiasvanderwerff Thank you for your answer.
